title: CU-Scout-Autoware-Docs
description: Documentation for working with the Scout and Autoware at Clarkson University
theme: just-the-docs

url: https://ChesterMK7.github.io/CU-Scout-Autoware-Docs

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"


nav_enabled: true

enable_copy_code_button: true

aux_links:
  CU_scout_nav_docs Repository: https://github.com/ChesterMK7/CU-Scout-Autoware-Docs
